### ISSUE TITLE
results of voc-15-5

### ISSUE THREAD

**Issue by Richardych** [arthurdouillard/CVPR2021_PLOP#19]
Hi, 

I run your code on voc-15-5, and get:
`Final Mean IoU 69.35
Average Mean IoU 74.84
Mean IoU first 75.25
Mean IoU last 50.47`

however, the paper stated is:
`75.73 51.71 70.09 75.19`

why the results are different and poor than the paper stated?

**Comment by arthurdouillard** [comment]
Paper vs your run:
- 75.73 vs 75.25
- 51.71 vs 50.47
- 69.35 vs 70.09
- 74.84 vs 75.19

The difference is always small (except maybe for old). It's probably due to the inherent randomness of the initialization (can change depending on cuda version, pytorch version, etc.).

I don't see that as a major difference. Have you look at 15-1 ?
